enableGlobalCache: true

nodeLinker: node-modules

npmRegistries:
  //npm.prod.contaazul.local:
    npmAlwaysAuth: false

npmRegistryServer: 'https://registry.npmjs.org/'

npmScopes:
  ca-tools-front:
    npmPublishRegistry: 'http://npm.prod.contaazul.local/'
    npmRegistryServer: 'http://npm.prod.contaazul.local/'
  contaazul:
    npmPublishRegistry: 'http://npm.prod.contaazul.local/'
    npmRegistryServer: 'http://npm.prod.contaazul.local/'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-engines.cjs
    spec: 'https://raw.githubusercontent.com/devoto13/yarn-plugin-engines/main/bundles/%40yarnpkg/plugin-engines.js'

unsafeHttpWhitelist:
  - '*.contaazul.local'

yarnPath: .yarn/releases/yarn-3.4.1.cjs
