name: Publish package

on:
  push:
    branches:
      - master

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'chore: release v')"

    steps:
      # Checkout the repo
      - name: Checkout
        uses: actions/checkout@v4

      # Configure git
      - name: Configure CI Git User
        run: |
          git config --global user.name "cacontinuos"
          git config --global user.email "ninjas@contaazul.com"

      # Setup Node.js build environment
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          registry-url: 'https://registry.npmjs.org'

      # Cache dependencies
      - name: Cache Dependencies
        uses: actions/cache@v4
        id: cache
        with:
          path: |
            **/node_modules
          key: yarn-${{ hashFiles('**/package.json', 'yarn.lock') }}

      # Install project dependencies
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn

      # Authenticate to NPM
      - name: Authenticate with Registry
        run: |
          npm config set registry https://registry.npmjs.org/
          echo "registry=https://registry.npmjs.org/" >> .npmrc
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" >> .npmrc

      # Release and publish version
      - name: Release version
        run: yarn release --ci --npm.skipChecks
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
